spring.application.name=automatizacion_gestion_respaldo

# Oracle Connection (Repository Database)
spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.username=rman_admin
# El password real se descifra con Jasypt
spring.datasource.password=ENC(tu_password_cifrado_aqui)
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# Hibernate / JPA (Auto-generate tables)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

# Jasypt Configuration (Key to decrypt passwords)
jasypt.encryptor.password=mi_clave_maestra_jasypt
